from pynput.keyboard import Key, Controller
from time import sleep

keyboard = Controller()

# Press and release space
keyboard.press(Key.cmd)
keyboard.release(Key.cmd)
sleep(1)
keyboard.type('Windows Defender Settings')
sleep(1)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
sleep(2)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
sleep(2)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
sleep(1)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
sleep(1)
keyboard.press(Key.space)
keyboard.release(Key.space)
sleep(1)
keyboard.press(Key.left)
keyboard.release(Key.left)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
